name: pytest

on:
  push:
  pull_request:

env:
  cache-version: v1

jobs:
  pytest:
    name: Run tests with pytest
    # 実行環境として `ubuntu-latest` という名前のものを選ぶ
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウトする
      # See: https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Cache pip
        uses: actions/cache@v1.0.0
        with:
          path: ~/.cache/pip
          key: ${{ env.cache-version }}-${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            $ {{ env.cache-version }}-${{ runner.os }}-pip-

        
      # pip そのものをインストールする
      - name: Install dependencies
        run: |
          pip install pytest
          if [ -f requirements.txt ]; 
            then pip install -r requirements.txt; 
          fi

      # pytest を実行する
      - name: Run Tests
        run: pytest tests/